spring:
  application:
    name: com.nhs.hr.management
  datasource:
    url: jdbc:mysql://localhost:3306/nhshrmanagement
    username: root
    password:
  jpa:
    hibernate.ddl-auto: create
    hibernate.format_sql: true
    generate-ddl: true
    show-sql: true
    properties.hibernate.dialect : org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8080

  